site_name: "fulmo-cookiecutter-poetry"
site_description: "A cookiecutter template for Python projects that use Poetry for its dependency management"
repo_url: "https://github.com/jexio/fulmo-cookiecutter-poetry"
site_url: "https://jexio.github.io/fulmo-cookiecutter-poetry"
site_author: "Gleb Glushkov"
edit_uri: "edit/main/docs/"
repo_name: "jexio/fulmo-cookiecutter-poetry"
copyright: 'Maintained by <a href="https://jexio.com">Gleb Glushkov</a>.'

nav:
  - Home:
    - Overview: index.md
    - Changelog: changelog.md
  - Features:
    - CI/CD with Github Actions: features/cicd.md
    - Linting & code quality: features/linting.md
    - Makefile: features/makefile.md
    - Dependency management with Poetry: features/poetry.md
    - Publishing to PyPi: features/publishing.md
    - Testing with Pytest: features/pytest.md
    - Test coverage with codecov: features/codecov.md
    - Documentation with MkDocs: features/mkdocs.md
    - Compatibility testing with Tox: features/tox.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md
plugins:
  - search
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jexio/fulmo-cookiecutter-poetry
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fulmo-cookiecutter-poetry/
markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
