repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

-   repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.7+
        exclude: ^{{cookiecutter.project_name}}
        args: ["--target-version", "py310", "--target-version", "py311"]

-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

-   repo: local
    hooks:

      - id: commitizen
        name: commitizen
        entry: cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]
